const ScreenName = {
    Login: "Login",
    Register: "Register",
    ActiveAccount: "ActiveAccount",
    Home: "Home",
    Profile: "Profile",
    TabMain: "TabMain",
    Search: "Search",
    AccountSettings: "AccountSettings",
    Order: "Order",
    Reviews: "Reviews",
    Shop: "Shop",
    Address: "Address",
    MyShop: "MyShop",
    MyProduct: "MyProduct",
    AddNewProduct: "AddNewProduct",
    DetailOrder: "DetailOrder",
    NewAddress: "NewAddress",
    Finance: "Finance",
    Deposits: "Deposits",
    Withdraw: "Withdraw",
    WithdrawalAccount: "WithdrawalAccount",
    Sales: "Sales",
    Pay: "Pay",
    Cart: "Cart",
    OrderProcessing: "OrderProcessing",
    PaymentMethods: "PaymentMethods",
    Detail: "Detail",
    TransactionHistory: "TransactionHistory",
}

export default ScreenName